### ISSUE TITLE
will you Add features switch ltsc 2021 and server2022

### ISSUE THREAD

**Issue by firo1603** [TheMCHK/HWIDGEN#6]
LTSC 2021 and server 2022 both build with 21H2
will you add features for this?

**Comment by revelator** [comment]
better clone it yourself ;) i think the maintainer has slipped the hook on this one.
should be possible to add the keys for the newer ltsc versions without to much hassle i reckon.

**Comment by firo1603** [comment]
ok  ,i will do it by myself
